version: '3.3'
services:
  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    restart: always
    container_name: ${CONTAINER_NAMESPACE}telegraf
    hostname: telegraf
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - default

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    restart: always
    container_name: ${CONTAINER_NAMESPACE}influxdb
    hostname: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - ./volumes/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb:/var/lib/influxdb:rw
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}influxdb
      nginx_proxy:

  chronograf:
    image: chronograf:${CHRONOGRAF_VERSION}
    restart: always
    container_name: ${CONTAINER_NAMESPACE}chronograf
    hostname: chronograf
    environment:
      - INFLUXDB_URL=http://${CONTAINER_NAMESPACE}influxdb:8086
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - KAPACITOR_URL=http://${CONTAINER_NAMESPACE}kapacitor:9092
      - KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER}
      - KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    ports:
     - "8888:8888"
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}chronograf
      nginx_proxy:

  kapacitor:
    image: kapacitor:${KAPACITOR_VERSION}
    restart: always
    container_name: ${CONTAINER_NAMESPACE}kapacitor
    hostname: kapacitor
    environment:
      - VIRTUAL_HOST=${KAPACITOR_HOST}
      - VIRTUAL_PORT=9092
      - KAPACITOR_INFLUXDB_ENABLED=true
      - KAPACITOR_INFLUXDB_NAME=telegraf
      - KAPACITOR_INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - KAPACITOR_INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}kapacitor
      nginx_proxy:

networks:
  nginx_proxy:
    external:
      name: nginx_proxy_default
